---
telegraf_output:
  - type: influxdb
    config:
      - urls = ["https://influx-server.weslyg.ru"]
      - database = "wazuh"
      - precision = "s"
      - password = "{{ secret_influx_password }}"
      - username = "reporter"

gitlab_runner_package_name: gitlab-ci-multi-runner
gitlab_runner_registration_token: '{{ secret_gitlab_registration_token }}'
gitlab_runner_coordinator_url: https://gitlab.com
gitlab_runner_runners:
  - name: 'htz-1'
    executor: docker
    docker_image: 'alpine'
    tags:
      - htz
      - docker
    docker_volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/cache'
    extra_configs:
      runners.docker:
        memory: 1024m
      runners.docker.sysctls:
        net.ipv4.ip_forward: '1'
  - name: 'htz-2'
    executor: docker
    docker_image: 'alpine'
    tags:
      - htz
      - docker
    docker_volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/cache'
    extra_configs:
      runners.docker:
        memory: 1024m
      runners.docker.sysctls:
        net.ipv4.ip_forward: '1'

package_list:
  - git
  - nano
  - curl
  - wget
  - nmap
  - zip
  - firewalld
  - python3
  - python3-dev
  - python3-pip

alias_block: |
  alias d='docker'
  alias dc='docker-compose'
  alias tailf='tail -f'

# port_opened:
#   - 9500/tcp
#   - 9000/tcp
#   - 5601/tcp
#   - 8089/tcp

telegraf_inputs: '{{ telegraf_weslyg_input }}'

telegraf_weslyg_input:
  - input: cpu
    config:
      - percpu = false
      - totalcpu = true
      - collect_cpu_time = true
      - fielddrop =
        ["time_guest","time_guest_nice","time_irq","time_nice","time_softirq","time_steal","usage_guest","usage_guest_nice","usage_irq","usage_nice","usage_softirq","usage_steal"]
      - interval = "2s"
  - input: disk
    config:
      - ignore_fs = ["tmpfs", "devtmpfs"]
  - input: io
  - input: mem
  - input: net
  - input: system
  - input: swap
  - input: netstat
  - input: net
  - input: mem
  - input: processes
  - input: docker
    config:
      - endpoint = "unix:///var/run/docker.sock"
      - gather_services = false
      - timeout = "5s"
      - perdevice = true
      - total = false
