version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 3005:3000
    depends_on:
      - mongo
    environment:
      - PORT=3000
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - SERVER_URL=3005
  mongo:
    image: mongo
    ports:
      - 27017:27017
