ARG NODE_VERSION
ARG PORT=80
FROM node:${NODE_VERSION}-alpine as builder

WORKDIR /app
COPY package.json yarn.lock /app/
RUN yarn install --cache-folder .yarn-cache --frozen-lockfile --ignore-scripts --network-timeout 100000

COPY . /app
RUN yarn client:build

FROM nginx:alpine
COPY --from=builder /app/dist/client /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE ${PORT}
CMD ["nginx", "-g", "daemon off;"]